const DecoCartActionTypes = {
    TOGGLE_DECOCART_HIDDEN: 'TOGGLE_DECOCART_HIDDEN',
    ADD_DECOITEM: 'ADD_DECOITEM',
    REMOVE_DECOITEM: 'REMOVE_DECOITEM',
    CLEAR_DECOITEM_FROM_CART: 'CLEAR_DECOITEM_FROM_CART',
    CLEAR_DECOCART: 'CLEAR_DECOCART',
    SET_DECOCART_FROM_FIREBASE: 'SET_DECOCART_FROM_FIREBASE',
    UPDATE_DECOCART_IN_FIREBASE: 'UPDATE_DECOCART_IN_FIREBASE'
}

export default DecoCartActionTypes;