const locations = [
    {label:"Aanwins AH",value:"Aanwins AH"},
    {label:"Abbotsford",value:"Abbotsford"},
    {label:"Aeroton",value:"Aeroton"},
    {label:"Alan Manor",value:"Alan Manor"},
    {label:"Albertskroon",value:"Albertskroon"},
    {label:"Albertville",value:"Albertville"},
    {label:"Aldara Park",value:"Aldara Park"},
    {label:"Allen's Nek",value:"Allen's Nek"},
    {label:"Alsef AH",value:"Alsef AH"},
    {label:"Alveda",value:"Alveda"},
    {label:"Amalgam",value:"Amalgam"},
    {label:"Ambot AH",value:"Ambot AH"},
    {label:"Amorosa",value:"Amorosa"},
    {label:"Aspen Hills Nature Estate",value:"Aspen Hills Nature Estate"},
    {label:"Atholl",value:"Atholl"},
    {label:"Auckland Park",value:"Auckland Park"},
    {label:"Bagleyston",value:"Bagleyston"},
    {label:"Barlow Park",value:"Barlow Park"},
    {label:"Bassonia",value:"Bassonia"},
    {label:"Bellairs Park",value:"Bellairs Park"},
    {label:"Bellevue",value:"Bellevue"},
    {label:"Bellevue East",value:"Bellevue East"},
    {label:"Benrose",value:"Benrose"},
    {label:"Berario",value:"Berario"},
    {label:"Bergbron",value:"Bergbron"},
    {label:"Bertrams",value:"Bertrams"},
    {label:"Beverley",value:"Beverley"},
    {label:"Beverley Gardens",value:"Beverley Gardens"},
    {label:"Bezuidenhout Valley",value:"Bezuidenhout Valley"},
    {label:"Birdhaven",value:"Birdhaven"},
    {label:"Birnam",value:"Birnam"},
    {label:"Blackheath",value:"Blackheath"},
    {label:"Blairgowrie",value:"Blairgowrie"},
    {label:"Bloubosrand",value:"Bloubosrand"},
    {label:"Booysens",value:"Booysens"},
    {label:"Booysens Reserve",value:"Booysens Reserve"},
    {label:"Bordeaux",value:"Bordeaux"},
    {label:"Boskruin",value:"Boskruin"},
    {label:"Bosmont",value:"Bosmont"},
    {label:"Bramley",value:"Bramley"},
    {label:"Bramley North",value:"Bramley North"},
    {label:"Bramley Park",value:"Bramley Park"},
    {label:"Bramley View",value:"Bramley View"},
    {label:"Brixton",value:"Brixton"},
    {label:"Broadacres AH",value:"Broadacres AH"},
    {label:"Bromhof",value:"Bromhof"},
    {label:"Bruma",value:"Bruma"},
    {label:"Bryanbrink",value:"Bryanbrink"},
    {label:"Bryanston",value:"Bryanston"},
    {label:"Buccleuch",value:"Buccleuch"},
    {label:"Bushwillow Park",value:"Bushwillow Park"},
    {label:"Carenvale",value:"Carenvale"},
    {label:"Cedar Lakes",value:"Cedar Lakes"},
    {label:"Cheltondale",value:"Cheltondale"},
    {label:"Chislehurston",value:"Chislehurston"},
    {label:"Chrisville",value:"Chrisville"},
    {label:"City and Suburban",value:"City and Suburban"},
    {label:"Claremont",value:"Claremont"},
    {label:"Cleveland",value:"Cleveland"},
    {label:"Comptonville",value:"Comptonville"},
    {label:"Constantia Kloof",value:"Constantia Kloof"},
    {label:"Corlett Gardens",value:"Corlett Gardens"},
    {label:"Coronationville",value:"Coronationville"},
    {label:"Cosmo City",value:"Cosmo City"},
    {label:"Cottesloe",value:"Cottesloe"},
    {label:"Country Life Park",value:"Country Life Park"},
    {label:"Craighall",value:"Craighall"},
    {label:"Craighall Park",value:"Craighall Park"},
    {label:"Cresta",value:"Cresta"},
    {label:"Creswell Park",value:"Creswell Park"},
    {label:"Croesus",value:"Croesus"},
    {label:"Crosby",value:"Crosby"},
    {label:"Crown",value:"Crown"},
    {label:"Crown Gardens",value:"Crown Gardens"},
    {label:"Crown Mine",value:"Crown Mine"},
    {label:"Crown North",value:"Crown North"},
    {label:"Crystal Gardens",value:"Crystal Gardens"},
    {label:"Cyrildene",value:"Cyrildene"},
    {label:"Daniel Brink Park",value:"Daniel Brink Park"},
    {label:"Darrenwood",value:"Darrenwood"},
    {label:"Davidsonville",value:"Davidsonville"},
    {label:"Delarey",value:"Delarey"},
    {label:"Denver",value:"Denver"},
    {label:"Dewetshof",value:"Dewetshof"},
    {label:"Discovery",value:"Discovery"},
    {label:"Doornfontein",value:"Doornfontein"},
    {label:"Dorelan",value:"Dorelan"},
    {label:"Douglasdale",value:"Douglasdale"},
    {label:"Droste Park",value:"Droste Park"},
    {label:"Dunkeld",value:"Dunkeld"},
    {label:"Dunsevern",value:"Dunsevern"},
    {label:"Durban Roodepoort Deep Gold Mine",value:"Durban Roodepoort Deep Gold Mine"},
    {label:"Duxberry",value:"Duxberry"},
    {label:"Eagle Canyon",value:"Eagle Canyon"},
    {label:"East Town",value:"East Town"},
    {label:"Eastgate",value:"Eastgate"},
    {label:"Edenburg",value:"Edenburg"},
    {label:"Eikenhof",value:"Eikenhof"},
    {label:"Eikenhof SP1",value:"Eikenhof SP1"},
    {label:"Elandspark",value:"Elandspark"},
    {label:"Eldorado Estate",value:"Eldorado Estate"},
    {label:"Electron",value:"Electron"},
    {label:"Emmarentia",value:"Emmarentia"},
    {label:"Evans Park",value:"Evans Park"},
    {label:"Fairland",value:"Fairland"},
    {label:"Fairmount",value:"Fairmount"},
    {label:"Fairmount Ridge",value:"Fairmount Ridge"},
    {label:"Fairvale",value:"Fairvale"},
    {label:"Fairview",value:"Fairview"},
    {label:"Fairway",value:"Fairway"},
    {label:"Fairwood",value:"Fairwood"},
    {label:"Fellside",value:"Fellside"},
    {label:"Ferndale",value:"Ferndale"},
    {label:"Ferreirasdorp",value:"Ferreirasdorp"},
    {label:"Fleurhof",value:"Fleurhof"},
    {label:"Floracliffe",value:"Floracliffe"},
    {label:"Florida",value:"Florida"},
    {label:"Florida Glen",value:"Florida Glen"},
    {label:"Florida Hills",value:"Florida Hills"},
    {label:"Florida Lake",value:"Florida Lake"},
    {label:"Florida North",value:"Florida North"},
    {label:"Florida Park",value:"Florida Park"},
    {label:"Florida View",value:"Florida View"},
    {label:"Fontainebleau",value:"Fontainebleau"},
    {label:"Fordsburg",value:"Fordsburg"},
    {label:"Forest Hill",value:"Forest Hill"},
    {label:"Forest Town",value:"Forest Town"},
    {label:"Formain",value:"Formain"},
    {label:"Founders Hill",value:"Founders Hill"},
    {label:"Fourways",value:"Fourways"},
    {label:"Fourways Gardens",value:"Fourways Gardens"},
    {label:"Frankenwald",value:"Frankenwald"},
    {label:"Franklin Roosevelt Park",value:"Franklin Roosevelt Park"},
    {label:"Freedom Park",value:"Freedom Park"},
    {label:"Gallo Manor",value:"Gallo Manor"},
    {label:"Georginia",value:"Georginia"},
    {label:"Gillview",value:"Gillview"},
    {label:"Glenadrienne SP1",value:"Glenadrienne SP1"},
    {label:"Glenadrienne SP2",value:"Glenadrienne SP2"},
    {label:"Glenanda",value:"Glenanda"},
    {label:"Glenesk",value:"Glenesk"},
    {label:"Glenhazel",value:"Glenhazel"},
    {label:"Glensan",value:"Glensan"},
    {label:"Glenvista",value:"Glenvista"},
    {label:"Greenside",value:"Greenside"},
    {label:"Greenside East",value:"Greenside East"},
    {label:"Greenstone Hill",value:"Greenstone Hill"},
    {label:"Greenstone Park",value:"Greenstone Park"},
    {label:"Gresswold",value:"Gresswold"},
    {label:"Greymont",value:"Greymont"},
    {label:"Groblerpark",value:"Groblerpark"},
    {label:"Haddon",value:"Haddon"},
    {label:"Hamberg",value:"Hamberg"},
    {label:"Harison Park",value:"Harison Park"},
    {label:"Harison View",value:"Harison View"},
    {label:"Harveston AH",value:"Harveston AH"},
    {label:"Hawkins Estate",value:"Hawkins Estate"},
    {label:"Helderkruin",value:"Helderkruin"},
    {label:"Heriotdale",value:"Heriotdale"},
    {label:"Highlands",value:"Highlands"},
    {label:"Highlands North",value:"Highlands North"},
    {label:"Homestead Park",value:"Homestead Park"},
    {label:"Honey Hill",value:"Honey Hill"},
    {label:"Honeydew Ridge",value:"Honeydew Ridge"},
    {label:"Hoogland",value:"Hoogland"},
    {label:"Horison",value:"Horison"},
    {label:"Houghton Estate",value:"Houghton Estate"},
    {label:"Hunters Hill A. H. SP",value:"Hunters Hill A. H. SP"},
    {label:"Hurlingham",value:"Hurlingham"},
    {label:"Hurlingham Gardens",value:"Hurlingham Gardens"},
    {label:"Hurst Hill",value:"Hurst Hill"},
    {label:"Hyde Park",value:"Hyde Park"},
    {label:"Illovo",value:"Illovo"},
    {label:"Inadan AH",value:"Inadan AH"},
    {label:"Inanda",value:"Inanda"},
    {label:"Industria",value:"Industria"},
    {label:"Industria North",value:"Industria North"},
    {label:"Industria West",value:"Industria West"},
    {label:"Jacanlee",value:"Jacanlee"},
    {label:"Jackal Creek Golf Estate",value:"Jackal Creek Golf Estate"},
    {label:"Jan Hofmeyer",value:"Jan Hofmeyer"},
    {label:"Johannesburg North",value:"Johannesburg North"},
    {label:"Judith's Paarl",value:"Judith's Paarl"},
    {label:"Jukskei Park",value:"Jukskei Park"},
    {label:"Kelland",value:"Kelland"},
    {label:"Kelvin",value:"Kelvin"},
    {label:"Kengies AH",value:"Kengies AH"},
    {label:"Kenilworth",value:"Kenilworth"},
    {label:"Kensington",value:"Kensington"},
    {label:"Kensington B",value:"Kensington B"},
    {label:"Kentview",value:"Kentview"},
    {label:"Kew",value:"Kew"},
    {label:"Kibler Park 1",value:"Kibler Park 1"},
    {label:"Kibler Park 2",value:"Kibler Park 2"},
    {label:"Killarney",value:"Killarney"},
    {label:"Kimbult AH",value:"Kimbult AH"},
    {label:"Kleve Hill Park",value:"Kleve Hill Park"},
    {label:"Klipfontein View",value:"Klipfontein View"},
    {label:"Klipriviersberg Estate",value:"Klipriviersberg Estate"},
    {label:"Klipriviersberg Nature Reserve",value:"Klipriviersberg Nature Reserve"},
    {label:"Klipspruit West",value:"Klipspruit West"},
    {label:"Kloofendal",value:"Kloofendal"},
    {label:"Kramerville",value:"Kramerville"},
    {label:"Kya Sand SP",value:"Kya Sand SP"},
    {label:"La Rochelle",value:"La Rochelle"},
    {label:"Lakeside",value:"Lakeside"},
    {label:"Langlaagte North",value:"Langlaagte North"},
    {label:"Laser Park",value:"Laser Park"},
    {label:"Lea Glen",value:"Lea Glen"},
    {label:"Liefde en Vrede",value:"Liefde en Vrede"},
    {label:"Linbro Park AH",value:"Linbro Park AH"},
    {label:"Lindberg Park",value:"Lindberg Park"},
    {label:"Linden",value:"Linden"},
    {label:"Lindhaven",value:"Lindhaven"},
    {label:"Linksfield",value:"Linksfield"},
    {label:"Linksfield Ridge",value:"Linksfield Ridge"},
    {label:"Linmeyer",value:"Linmeyer"},
    {label:"Little Falls",value:"Little Falls"},
    {label:"Lombardy East",value:"Lombardy East"},
    {label:"Lombardy West",value:"Lombardy West"},
    {label:"Lone Hill",value:"Lone Hill"},
    {label:"Longdale",value:"Longdale"},
    {label:"Lorentzville",value:"Lorentzville"},
    {label:"Lyme Park",value:"Lyme Park"},
    {label:"Lyndhurst",value:"Lyndhurst"},
    {label:"Magaliessig",value:"Magaliessig"},
    {label:"Malanshof",value:"Malanshof"},
    {label:"Malvern",value:"Malvern"},
    {label:"Manufacta",value:"Manufacta"},
    {label:"Maraisburg",value:"Maraisburg"},
    {label:"Marlboro Gardens",value:"Marlboro Gardens"},
    {label:"Maroeladal",value:"Maroeladal"},
    {label:"Marshalltown",value:"Marshalltown"},
    {label:"Martindale",value:"Martindale"},
    {label:"Maryvale",value:"Maryvale"},
    {label:"Matholesville",value:"Matholesville"},
    {label:"Mayfair",value:"Mayfair"},
    {label:"Mayfair West",value:"Mayfair West"},
    {label:"Mayfield Park",value:"Mayfield Park"},
    {label:"Melrose",value:"Melrose"},
    {label:"Melrose Estate",value:"Melrose Estate"},
    {label:"Melville",value:"Melville"},
    {label:"Meredale",value:"Meredale"},
    {label:"Modderfontein",value:"Modderfontein"},
    {label:"Modderfontein AH",value:"Modderfontein AH"},
    {label:"Moffat Park",value:"Moffat Park"},
    {label:"Moffat View",value:"Moffat View"},
    {label:"Mondeor",value:"Mondeor"},
    {label:"Montclare",value:"Montclare"},
    {label:"Montgomery Park",value:"Montgomery Park"},
    {label:"Montroux",value:"Montroux"},
    {label:"Moodie Hill",value:"Moodie Hill"},
    {label:"Moret",value:"Moret"},
    {label:"Morningside",value:"Morningside"},
    {label:"Morningside Manor",value:"Morningside Manor"},
    {label:"Mostyn Park AH",value:"Mostyn Park AH"},
    {label:"Mountain View",value:"Mountain View"},
    {label:"Mulbarton",value:"Mulbarton"},
    {label:"Nancefield",value:"Nancefield"},
    {label:"Nancefield Industrial",value:"Nancefield Industrial"},
    {label:"Nasrec",value:"Nasrec"},
    {label:"Naturena",value:"Naturena"},
    {label:"Needwood",value:"Needwood"},
    {label:"New Brighton",value:"New Brighton"},
    {label:"New Centre",value:"New Centre"},
    {label:"New Doornfontein",value:"New Doornfontein"},
    {label:"Newclare",value:"Newclare"},
    {label:"Newlands",value:"Newlands"},
    {label:"Newtown",value:"Newtown"},
    {label:"Noordhang",value:"Noordhang"},
    {label:"Norscot",value:"Norscot"},
    {label:"North Doornfontein",value:"North Doornfontein"},
    {label:"North Riding",value:"North Riding"},
    {label:"North Riding AH",value:"North Riding AH"},
    {label:"Northcliff",value:"Northcliff"},
    {label:"Northgate",value:"Northgate"},
    {label:"Northworld",value:"Northworld"},
    {label:"Northworld AH",value:"Northworld AH"},
    {label:"Norwood",value:"Norwood"},
    {label:"Oakdene",value:"Oakdene"},
    {label:"Oaklands",value:"Oaklands"},
    {label:"Observatory",value:"Observatory"},
    {label:"Olivedale",value:"Olivedale"},
    {label:"Ontdekkers Park",value:"Ontdekkers Park"},
    {label:"Ophirton",value:"Ophirton"},
    {label:"Orange Grove",value:"Orange Grove"},
    {label:"Orchards",value:"Orchards"},
    {label:"Ormonde",value:"Ormonde"},
    {label:"Ormonde View",value:"Ormonde View"},
    {label:"Paarlshoop",value:"Paarlshoop"},
    {label:"Pageview",value:"Pageview"},
    {label:"Palmlands AH",value:"Palmlands AH"},
    {label:"Park Central",value:"Park Central"},
    {label:"Parkhurst",value:"Parkhurst"},
    {label:"Parkmore",value:"Parkmore"},
    {label:"Parktown",value:"Parktown"},
    {label:"Parktown North",value:"Parktown North"},
    {label:"Parkview",value:"Parkview"},
    {label:"Parkwood",value:"Parkwood"},
    {label:"Paulshof",value:"Paulshof"},
    {label:"Percelia Estate",value:"Percelia Estate"},
    {label:"Petervale",value:"Petervale"},
    {label:"Pierneef Park",value:"Pierneef Park"},
    {label:"Pine Park",value:"Pine Park"},
    {label:"Pine Slopes AH",value:"Pine Slopes AH"},
    {label:"Poortview AH",value:"Poortview AH"},
    {label:"President Ridge",value:"President Ridge"},
    {label:"Princess",value:"Princess"},
    {label:"Princess AH",value:"Princess AH"},
    {label:"Prolecon",value:"Prolecon"},
    {label:"Queenshaven",value:"Queenshaven"},
    {label:"Quellerina",value:"Quellerina"},
    {label:"Radiokop",value:"Radiokop"},
    {label:"Raedene Estate",value:"Raedene Estate"},
    {label:"Rand Lease Gold Mine",value:"Rand Lease Gold Mine"},
    {label:"Randpark",value:"Randpark"},
    {label:"Randpark Ridge",value:"Randpark Ridge"},
    {label:"Randview",value:"Randview"},
    {label:"Raumarais Park",value:"Raumarais Park"},
    {label:"Reefhaven",value:"Reefhaven"},
    {label:"Regents Park",value:"Regents Park"},
    {label:"Rembrandt Park",value:"Rembrandt Park"},
    {label:"Rembrandt Ridge",value:"Rembrandt Ridge"},
    {label:"Reuven",value:"Reuven"},
    {label:"Rewlatch",value:"Rewlatch"},
    {label:"Richmond",value:"Richmond"},
    {label:"Ridgeway",value:"Ridgeway"},
    {label:"Risana",value:"Risana"},
    {label:"Risidale",value:"Risidale"},
    {label:"Risipark AH",value:"Risipark AH"},
    {label:"River Club",value:"River Club"},
    {label:"Riverbend AH",value:"Riverbend AH"},
    {label:"Riverlea",value:"Riverlea"},
    {label:"Riviera",value:"Riviera"},
    {label:"Rivonia",value:"Rivonia"},
    {label:"Robertsham",value:"Robertsham"},
    {label:"Robertville",value:"Robertville"},
    {label:"Robin Acres",value:"Robin Acres"},
    {label:"Robin Hills",value:"Robin Hills"},
    {label:"Robindale",value:"Robindale"},
    {label:"Roodekrans",value:"Roodekrans"},
    {label:"Roodekrans AH",value:"Roodekrans AH"},
    {label:"Roodepoort SP",value:"Roodepoort SP"},
    {label:"Roodeport North",value:"Roodeport North"},
    {label:"Roodeport West",value:"Roodeport West"},
    {label:"Roseacre",value:"Roseacre"},
    {label:"Rosebank",value:"Rosebank"},
    {label:"Rosettenville",value:"Rosettenville"},
    {label:"Rosherville",value:"Rosherville"},
    {label:"Rossmore",value:"Rossmore"},
    {label:"Rouxville",value:"Rouxville"},
    {label:"Ruimsig",value:"Ruimsig"},
    {label:"Ruimsig AH",value:"Ruimsig AH"},
    {label:"Ruiterhof",value:"Ruiterhof"},
    {label:"Sandhurst",value:"Sandhurst"},
    {label:"Sandown",value:"Sandown"},
    {label:"Sandringham",value:"Sandringham"},
    {label:"Savoy Estate",value:"Savoy Estate"},
    {label:"Saxonwold",value:"Saxonwold"},
    {label:"Sebenza",value:"Sebenza"},
    {label:"Selby",value:"Selby"},
    {label:"Selwyn",value:"Selwyn"},
    {label:"Sharonlea",value:"Sharonlea"},
    {label:"Silvamonte",value:"Silvamonte"},
    {label:"Simba",value:"Simba"},
    {label:"Slovo Park",value:"Slovo Park"},
    {label:"Sonnedal AH",value:"Sonnedal AH"},
    {label:"Sonneglans",value:"Sonneglans"},
    {label:"South Hills",value:"South Hills"},
    {label:"South Kensington",value:"South Kensington"},
    {label:"Southdale",value:"Southdale"},
    {label:"Southgate",value:"Southgate"},
    {label:"Springfield",value:"Springfield"},
    {label:"Steeledale",value:"Steeledale"},
    {label:"Stormill",value:"Stormill"},
    {label:"Stratford",value:"Stratford"},
    {label:"Strathavon",value:"Strathavon"},
    {label:"Strijdompark",value:"Strijdompark"},
    {label:"Strubensvallei",value:"Strubensvallei"},
    {label:"Suideroord",value:"Suideroord"},
    {label:"Sundowner",value:"Sundowner"},
    {label:"Sundowner Ext",value:"Sundowner Ext"},
    {label:"Sunningdale Ridge",value:"Sunningdale Ridge"},
    {label:"Sunninghill",value:"Sunninghill"},
    {label:"Sunset Acres",value:"Sunset Acres"},
    {label:"Sydenham",value:"Sydenham"},
    {label:"Talboton",value:"Talboton"},
    {label:"Technikon",value:"Technikon"},
    {label:"The Gardens",value:"The Gardens"},
    {label:"The Hill",value:"The Hill"},
    {label:"The Woodlands",value:"The Woodlands"},
    {label:"Theta",value:"Theta"},
    {label:"Thornhill Estate",value:"Thornhill Estate"},
    {label:"Towerby",value:"Towerby"},
    {label:"Townsview",value:"Townsview"},
    {label:"Tres Jolie AH",value:"Tres Jolie AH"},
    {label:"Triomf",value:"Triomf"},
    {label:"Troyeville",value:"Troyeville"},
    {label:"Tulisa Park",value:"Tulisa Park"},
    {label:"Turf Club",value:"Turf Club"},
    {label:"Turffontein",value:"Turffontein"},
    {label:"Uitsaaisentrum",value:"Uitsaaisentrum"},
    {label:"Unigray",value:"Unigray"},
    {label:"Valeriedene",value:"Valeriedene"},
    {label:"Vandia Grove",value:"Vandia Grove"},
    {label:"Victoria",value:"Victoria"},
    {label:"Victory Park",value:"Victory Park"},
    {label:"Viewcrest",value:"Viewcrest"},
    {label:"Village Main Reef Gold Mine",value:"Village Main Reef Gold Mine"},
    {label:"Vrededorp",value:"Vrededorp"},
    {label:"Waterval Estate",value:"Waterval Estate"},
    {label:"Waverley",value:"Waverley"},
    {label:"Weltevredenpark",value:"Weltevredenpark"},
    {label:"Wendywood",value:"Wendywood"},
    {label:"West Turffontein",value:"West Turffontein"},
    {label:"Westcliff",value:"Westcliff"},
    {label:"Westfield",value:"Westfield"},
    {label:"Whiteridge",value:"Whiteridge"},
    {label:"Wibsey Dip",value:"Wibsey Dip"},
    {label:"Wierda Valley",value:"Wierda Valley"},
    {label:"Wilfordon AH",value:"Wilfordon AH"},
    {label:"Wilgeheuwel",value:"Wilgeheuwel"},
    {label:"Willowbrook",value:"Willowbrook"},
    {label:"Willowild",value:"Willowild"},
    {label:"Wilro Park",value:"Wilro Park"},
    {label:"Winchester Hills",value:"Winchester Hills"},
    {label:"Windsor East",value:"Windsor East"},
    {label:"Windsor Glen",value:"Windsor Glen"},
    {label:"Windsor West",value:"Windsor West"},
    {label:"Winston Ridge",value:"Winston Ridge"},
    {label:"Witkoppen",value:"Witkoppen"},
    {label:"Witpoortjie",value:"Witpoortjie"},
    {label:"Wolhuter",value:"Wolhuter"},
    {label:"Woodmead",value:"Woodmead"},
    {label:"Wynberg",value:"Wynberg"},
    {label:"Zandspruit SP",value:"Zandspruit SP"},
    {label:"Zonnehoewe AH",value:"Zonnehoewe AH"}    
];

export default locations;