const locations = [
    {label:"Aeroton",value:"Aeroton"},
    {label:"Alan",value:"Alan"},
    {label:"Aspen",value:"Aspen"},
    {label:"Bellevue",value:"Bellevue"},
    {label:"Benrose",value:"Benrose"},
    {label:"Berea",value:"Berea"},
    {label:"Bertrams",value:"Bertrams"},
    {label:"Braamfontein",value:"Braamfontein"},
    {label:"Chrisville",value:"Chrisville"},
    {label:"Crosby",value:"Crosby"},
    {label:"Crown Gardens",value:"Crown Gardens"},
    {label:"Crown",value:"Crown"},
    {label:"Doornfontein",value:"Doornfontein"},
    {label:"Droste",value:"Droste"},
    {label:"Eagles Nest",value:"Eagles Nest"},
    {label:"Eastcliff",value:"Eastcliff"},
    {label:"Elandspark",value:"Elandspark"},
    {label:"Elcedes",value:"Elcedes"},
    {label:"Electron",value:"Electron"},
    {label:"Elladoone",value:"Elladoone"},
    {label:"Evans Park",value:"Evans Park"},
    {label:"Fairview",value:"Fairview"},
    {label:"Ferreirasdorp",value:"Ferreirasdorp"},
    {label:"Fordsburg",value:"Fordsburg"},
    {label:"Forest Hill",value:"Forest Hill"},
    {label:"Framton",value:"Framton"},
    {label:"Gillview",value:"Gillview"},
    {label:"Glenanda",value:"Glenanda"},
    {label:"Glenesk",value:"Glenesk"},
    {label:"Glenvista",value:"Glenvista"},
    {label:"Haddon",value:"Haddon"},
    {label:"Heriotdale",value:"Heriotdale"},
    {label:"Highlands",value:"Highlands"},
    {label:"Hillbrow",value:"Hillbrow"},
    {label:"Homestead Park",value:"Homestead Park"},
    {label:"Houghton Estate",value:"Houghton Estate"},
    {label:"Joubert",value:"Joubert"},
    {label:"Judith's",value:"Judith's"},
    {label:"Kenilworth",value:"Kenilworth"},
    {label:"Kensington",value:"Kensington"},
    {label:"Kibler",value:"Kibler"},
    {label:"Klipriviersberg",value:"Klipriviersberg"},
    {label:"Langlaagte",value:"Langlaagte"},
    {label:"Liefde",value:"Liefde"},
    {label:"Lindberg",value:"Lindberg"},
    {label:"Linmeyer",value:"Linmeyer"},
    {label:"Lorentzville",value:"Lorentzville"},
    {label:"Malvern",value:"Malvern"},
    {label:"Marshalls",value:"Marshalls"},
    {label:"Marshalltown",value:"Marshalltown"},
    {label:"Mayfair",value:"Mayfair"},
    {label:"Mayfield",value:"Mayfield"},
    {label:"Meredale",value:"Meredale"},
    {label:"Moffat",value:"Moffat"},
    {label:"Mondeor",value:"Mondeor"},
    {label:"Mulbarton",value:"Mulbarton"},
    {label:"Nasrec",value:"Nasrec"},
    {label:"Newtown",value:"Newtown"},
    {label:"North Doornfontein",value:"North Doornfontein"},
    {label:"Oakdene",value:"Oakdene"},
    {label:"Observatory",value:"Observatory"},
    {label:"Ophirton",value:"Ophirton"},
    {label:"Ormonde",value:"Ormonde"},
    {label:"Pageview",value:"Pageview"},
    {label:"Park",value:"Park"},
    {label:"Parktown",value:"Parktown"},
    {label:"Patlynn",value:"Patlynn"},
    {label:"Prolecon",value:"Prolecon"},
    {label:"Randview",value:"Randview"},
    {label:"Regency",value:"Regency"},
    {label:"Regents",value:"Regents"},
    {label:"Reuven",value:"Reuven"},
    {label:"Rewlatch",value:"Rewlatch"},
    {label:"Reynolds",value:"Reynolds"},
    {label:"Ridgeway",value:"Ridgeway"},
    {label:"Riepen",value:"Riepen"},
    {label:"Risana",value:"Risana"},
    {label:"Rispark",value:"Rispark"},
    {label:"Robertsham",value:"Robertsham"},
    {label:"Roseacre",value:"Roseacre"},
    {label:"Rosettenville",value:"Rosettenville"},
    {label:"Salisbury",value:"Salisbury"},
    {label:"Selby",value:"Selby"},
    {label:"South",value:"South"},
    {label:"Southdale",value:"Southdale"},
    {label:"Southfork",value:"Southfork"},
    {label:"Southgate",value:"Southgate"},
    {label:"Spes",value:"Spes"},
    {label:"Springfield",value:"Springfield"},
    {label:"Stafford",value:"Stafford"},
    {label:"Steeledale",value:"Steeledale"},
    {label:"Suideroord",value:"Suideroord"},
    {label:"The",value:"The"},
    {label:"The Hill",value:"The Hill"},
    {label:"Theta",value:"Theta"},
    {label:"Towerby",value:"Towerby"},
    {label:"Townsview",value:"Townsview"},
    {label:"Troyeville",value:"Troyeville"},
    {label:"Tulisa",value:"Tulisa"},
    {label:"Turf",value:"Turf"},
    {label:"Turffontein",value:"Turffontein"},
    {label:"Parktown",value:"Parktown"}    
];

export default locations;